# Generated by Django 3.1.6 on 2021-05-02 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre_fantasia', models.CharField(max_length=100)),
                ('denominacion_legal', models.CharField(blank=True, max_length=100)),
                ('cuit', models.PositiveBigIntegerField()),
                ('medio_pago', models.CharField(max_length=300)),
                ('correo', models.EmailField(max_length=100)),
                ('nro_wpp', models.CharField(blank=True, max_length=100)),
                ('telefonos_call', models.CharField(blank=True, max_length=100)),
                ('mensaje_extra', models.CharField(blank=True, max_length=300)),
                ('paleta_color_1', models.CharField(max_length=7)),
                ('paleta_color_2', models.CharField(blank=True, max_length=7)),
                ('paleta_texto', models.CharField(blank=True, max_length=7)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, '------------------'), (1, 'Empresa_Deuda'), (2, 'Empresa_Equipos'), (3, 'Admin'), (4, 'Admingral')], default=0)),
                ('dni', models.PositiveIntegerField()),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(max_length=50)),
                ('telefonos_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ManyToManyField(blank=True, to='vnc.Empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vnc.localidad')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vnc.provincia'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sucursal',
            field=models.ManyToManyField(blank=True, to='vnc.Sucursal'),
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_cliente', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('hora_hasta', models.TimeField(blank=True, null=True)),
                ('tipo_vivienda', models.CharField(choices=[('DEPTO', 'DEPTO'), ('CASA', 'CASA'), ('OTRO', 'OTRO')], default='DEPTO', max_length=10)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('nro', models.PositiveIntegerField(blank=True, null=True)),
                ('piso', models.PositiveIntegerField(blank=True, null=True)),
                ('entre_calle_1', models.CharField(blank=True, max_length=100, null=True)),
                ('entre_calle_2', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=25, null=True)),
                ('extra_elem', models.CharField(blank=True, max_length=300, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vnc.empresa')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vnc.localidad')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vnc.provincia')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vnc.sucursal')),
            ],
        ),
    ]
