# Generated by Django 3.1.6 on 2021-05-02 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromiso',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vnc.sucursal'),
        ),
    ]
