# Generated by Django 3.1.6 on 2021-05-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0002_auto_20210502_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromiso',
            name='id_deuda',
            field=models.PositiveIntegerField()
        ),
    ]
