# Generated by Django 3.1.6 on 2021-05-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0003_compromiso_id_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='elem_extra',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
