# Generated by Django 3.1.6 on 2021-05-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0004_empresa_elem_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromiso',
            name='tipo_deuda',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
