# Generated by Django 3.1.6 on 2021-05-26 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0005_compromiso_tipo_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromiso',
            name='tipo_deuda',
        ),
    ]
