# Generated by Django 3.2.3 on 2021-06-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0006_remove_compromiso_tipo_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromiso',
            name='tipo_compromiso',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
