# Generated by Django 3.2.3 on 2021-06-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0007_compromiso_tipo_compromiso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromiso',
            name='extra_elem',
        ),
        migrations.AddField(
            model_name='compromiso',
            name='equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='permite_entrega',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='permite_retiro',
            field=models.BooleanField(default=True),
        ),
    ]
