# Generated by Django 3.2.3 on 2021-06-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0008_auto_20210614_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioempresa',
            name='empresa',
        ),
        migrations.AddField(
            model_name='usuarioempresa',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vnc.empresa'),
            preserve_default=False,
        ),
    ]
