# Generated by Django 3.2.3 on 2021-06-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0009_auto_20210614_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='sucursal',
        ),
    ]
