# Generated by Django 3.2.3 on 2021-06-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0010_remove_empresa_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromiso',
            name='sucursal',
        ),
    ]
