# Generated by Django 3.2.4 on 2021-06-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0011_remove_compromiso_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromiso',
            name='tipo_vivienda',
            field=models.CharField(blank=True, choices=[('DEPTO', 'DEPTO'), ('CASA', 'CASA'), ('OTRO', 'OTRO')], default='DEPTO', max_length=10, null=True),
        ),
    ]
