# Generated by Django 3.2.4 on 2021-07-09 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0012_alter_compromiso_tipo_vivienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='hora_maxima',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='empresa',
            name='hora_minima',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
