# Generated by Django 3.2.4 on 2021-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0013_auto_20210709_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nro_wpp',
            field=models.CharField(max_length=100),
        ),
    ]
