# Generated by Django 3.2.4 on 2021-07-13 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0015_auto_20210713_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioempresa',
            name='dni',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
