# Generated by Django 3.2.4 on 2021-07-13 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0016_alter_usuarioempresa_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioempresa',
            name='dni',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(39000000000)]),
        ),
    ]
