# Generated by Django 3.2.4 on 2021-07-13 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0017_alter_usuarioempresa_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromiso',
            name='calle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='entre_calle_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='entre_calle_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='nro',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='compromiso',
            name='piso',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(max_length=35),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(20000000000), django.core.validators.MaxValueValidator(39999999999)]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nro_wpp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='nombre',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
