# Generated by Django 3.2.5 on 2021-08-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0018_auto_20210713_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioempresa',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, '------------------'), (1, 'Gestión de deudas'), (2, 'Gestion de equipos'), (3, 'Admin'), (4, 'Admin general')], default=0),
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
