# Generated by Django 3.2.5 on 2021-08-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0019_auto_20210802_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
