# Generated by Django 3.2.5 on 2021-09-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0020_alter_localidad_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['nombre']},
        ),
    ]
