# Generated by Django 3.2.5 on 2021-10-17 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0021_auto_20210907_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compromiso',
            old_name='calle',
            new_name='callenro',
        ),
        migrations.RemoveField(
            model_name='compromiso',
            name='nro',
        ),
        migrations.AddField(
            model_name='compromiso',
            name='departamento',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
