# Generated by Django 3.2.5 on 2021-10-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0022_auto_20211017_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioempresa',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, '------------------'), (1, 'Gestión de deudas'), (2, 'Gestión de equipos'), (3, 'Admin'), (4, 'Admin general')], default=0),
        ),
    ]
