# Generated by Django 3.2.5 on 2021-10-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0023_alter_usuarioempresa_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromiso',
            name='departamento',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
