# Generated by Django 3.2.5 on 2021-10-20 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0024_alter_compromiso_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromiso',
            name='dni_cliente',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(39000000000)]),
        ),
    ]
