# Generated by Django 3.2.5 on 2021-10-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnc', '0025_alter_compromiso_dni_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromiso',
            name='id_deuda',
            field=models.PositiveBigIntegerField(),
        ),
    ]
